default:
  tags: 
    - $NOM_EQUIPE 
  interruptible: true
image: 
  name: pandoc/extra
  entrypoint: ["/bin/sh", "-c"]
stages: 
  - build
  - deploy

build:
  stage: build
  script:
    - pandoc --pdf-engine xelatex --metadata-file pandoc-assets/meta.yml --template pandoc-assets/templates/eisvogel.tex --from markdown+yaml_metadata_block+raw_html+rebase_relative_paths --output=Referentiel-ECOCONCEPTION.pdf introduction/*.md strategie/*.md ux/*.md ui/*.md code/*.md architecture/*.md
  artifacts:
    paths:
      - Referentiel-ECOCONCEPTION.pdf

pages:
  stage: deploy
  tags:
    - gitlab-pages
  script:
    - echo "publication"
    - mkdir public
    - cp Referentiel-ECOCONCEPTION.pdf public
    - echo "<html><body><h1>Référentiel d'éco-conception</h1><a href=\"Referentiel-ECOCONCEPTION.pdf\">Référentiel d'écoconception</a></body></html>" > public/index.html
  artifacts:
    paths:
      - public
