---
title: "Référentiel des bonnes pratiques d’écoconception"
subtitle: "Appliqué aux services numériques"
author: "Auteur: France Travail"
date: "2024-10-01"
subject: "Bas carbone"
keywords: [Bas carbone, éco-conception]
lang: fr-FR
titlepage: true
titlepage-color: "FFFFFF"
titlepage-text-color: "393F7F"
titlepage-rule-color: "393F7F"
titlepage-rule-height: 2
#titlepage-logo: img/Republique-francaise-logo.jpg
page-background:
page-background-opacity:
links-as-notes: true
lot: false
lof: false
toc: false
book: false
classoption: oneside
geometry: a4paper,margin=2cm
mainfont: Marianne-Regular.otf
mainfontoptions:
    - Path=./pandoc-assets/fonts/
    - Scale=1.0
    - BoldFont=Marianne-Bold.otf
    - ItalicFont=Marianne-RegularItalic.otf
    - BoldItalicFont=Marianne-BoldItalic.otf
header-left:
header-center:
header-right:
footer-left: "France Travail"
footer-center: "License: Creative Common"
footer-right:
subparagraph: true
listings-disable-line-numbers: true
listings-no-page-break: false
disable-header-and-footer: false
header-includes: |
  \usepackage{sectsty}
  \sectionfont{\clearpage}
---
