name: Generate pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: create file list
        id: files_list
        run: |
#          echo "Lorem ipsum" > lorem_1.md  # create two example files
#          echo "dolor sit amet" > lorem_2.md
          mkdir output  # create output dir
#          echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT
          $GITHUB_OUTPUT=introduction/*.md strategie/*.md ux/*.md ui/*.md code/*.md architecture/*.md

      - uses: docker://pandoc/latex
        with:
          args: --output=output/Referentiel-ECOCONCEPTION.pdf ${{ steps.files_list.outputs.files }} --metadata-file pandoc-assets/meta.yml --pdf-engine xelatex --metadata-file pandoc-assets/meta.yml --template pandoc-assets/templates/eisvogel.tex --from markdown+yaml_metadata_block+raw_html+rebase_relative_paths
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
